This is the code of "BERT Error Detection for STPA" (BEDS) Pipeline.

This Python Notebook was created and evaluated in Google Colab Pro (A100 GPU).

This code can be found in the GitHub repository:
https://github.com/andreyokamura-unicamp/BEDS-Pipeline

The BERT models for each Pipeline step trained in this notebook can be found in
https://huggingface.co/andreyunic23


Corresponding Author: A.T. Okamura

In [ ]:
# !pip install datasets
# !pip install evaluate
# !pip install sentence-transformers==3.1.1
# !pip install transformers==4.45.2

In [ ]:
import time
import pandas as pd
import numpy as np
from torch.nn import functional as F
import torch
from datasets import Dataset

from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import ConfusionMatrixDisplay

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer, AutoTokenizer, DataCollatorWithPadding
import evaluate

from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
    losses,
)

In [ ]:
# @title Language Model Preset
model_preset = "BERT" # @param ["BERT","DistilBERT","ModernBERT"]

In [ ]:
# Setting seed variables

random_state = 0

In [ ]:
# Define input file name here:
file_name = 'stpa-dataset.csv'

# Uncomment 4 lines below if using Google Drive
# from google.colab import drive
# drive.mount('/content/drive')
# drive_path = '/content/drive/MyDrive/Colab Notebooks/'
# file_name = drive_path+file_name

df = pd.read_csv(file_name, index_col=False, delimiter=',')

# remove unnecessary columns for training
df.drop(['domain', 'year', 'title', 'source', 'slide'], inplace=True, axis=1)
print(df.head())

                                            sentence       label validity  \
0  A collision between the ACROBOTER robotic plat...  constraint    valid
1   A non‐patient is injured or killed by radiation.        loss  invalid
2  A nonpatient is injured or killed in the proce...        loss  invalid
3  A pair of controlled aircraft violates minimum...      hazard    valid
4  A person or worker is standing/working under o...      hazard  invalid

      faults
0      valid
1  condition
2  condition
3      valid
4    rewrite

#Explore the dataset

In [ ]:
test_df = df.copy()
print(test_df[['sentence','faults']])

                                               sentence     faults
0     A collision between the ACROBOTER robotic plat...      valid
1      A non‐patient is injured or killed by radiation.  condition
2     A nonpatient is injured or killed in the proce...  condition
3     A pair of controlled aircraft violates minimum...      valid
4     A person or worker is standing/working under o...    rewrite
...                                                 ...        ...
1079    Avoid flight in altitude below permitted limit.        not
1080            System is capable of defending threats.        not
1081                     Verify if the runway is empty.        not
1082       Sudden braking olny in emergency situations.        not
1083        Vehicle overtaking only when road is empty.        not

[1084 rows x 2 columns]

In [ ]:
# Dataset overview
df.head()

# Class distribution of each target column
print(df.label.value_counts())
print('\n')
print(df.validity.value_counts())
print('\n')
print(df.faults.value_counts())

label
hazard        424
constraint    369
loss          291
Name: count, dtype: int64


validity
valid      780
invalid    304
Name: count, dtype: int64


faults
valid        780
rewrite      122
not           77
condition     60
accident      45
Name: count, dtype: int64

In [ ]:
# Distribution of valid and invalid sentences for each class
out = df.groupby('label')['validity'].value_counts(normalize=False)
print(out)
print('\n')

# Length of the longest sentence in the dataset
print(df.sentence.str.len().max())

label       validity
constraint  valid       301
            invalid      68
hazard      valid       287
            invalid     137
loss        valid       192
            invalid      99
Name: count, dtype: int64


270

In [ ]:
# Generate list of valid examples for sentence similarity calculation (for use in execution example)

valid_loss_reference = df[df.label.isin(['loss']) & df.validity.isin(['valid'])]['sentence'].drop_duplicates()
valid_hazard_reference = df[df.label.isin(['hazard']) & df.validity.isin(['valid'])]['sentence'].drop_duplicates()
valid_constraint_reference = df[df.label.isin(['constraint']) & df.validity.isin(['valid'])]['sentence'].drop_duplicates()

valid_loss_reference.to_csv('valid_loss_reference.csv',index=False, header=False, sep=',')
valid_hazard_reference.to_csv('valid_hazard_reference.csv',index=False, header=False, sep=',')
valid_constraint_reference.to_csv('valid_constraint_reference.csv',index=False, header=False, sep=',')

In [ ]:
step1_labels = ['loss', 'hazard', 'constraint']
step2_labels = ['valid', 'invalid']
step3_labels = ['rewrite', 'not', 'condition', 'accident', 'valid']


# Convert target labels to int as input for BERT prediction target
def label_to_int(df, name, labels):
  aux_df = df.copy()
  for i in range(len(aux_df[name])):
    aux_df.loc[i,name] = labels.index(aux_df.loc[i,name])
  return aux_df

In [ ]:
def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)
  precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')
  acc = accuracy_score(labels, preds)
  return {
  'accuracy': acc,
  'f1': f1,
  'precision': precision,
  'recall': recall
  }

# Path to save model
path = '/content/drive/MyDrive/Colab Notebooks/models/TEST/'

match model_preset:
  case 'BERT':
    model_name = "google-bert/bert-base-uncased"
  case 'DistilBERT':
    model_name = "distilbert/distilbert-base-uncased"
  case 'ModernBERT':
    model_name = "answerdotai/ModernBERT-base"


tokenizer = AutoTokenizer.from_pretrained(model_name)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
# Rename target column, convert label to int and convert to Dataset class
def format_dataset(df):
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)
  return Dataset.from_pandas(df)

# Transform input into embedding
def tokenize_function(examples):
    return tokenizer(examples['sentence'], truncation=True, padding='max_length', max_length=512, return_tensors='pt')


def train_model(train_dataset, test_dataset, num_labels):

  train_dataset = format_dataset(train_dataset)
  test_dataset = format_dataset(test_dataset)

  train_dataset = train_dataset.map(tokenize_function, batched=True)
  test_dataset = test_dataset.map(tokenize_function, batched=True)

  model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

  training_args = TrainingArguments(
      output_dir="beds_model",
      learning_rate=2e-5,
      per_device_train_batch_size=16,
      per_device_eval_batch_size=16,
      num_train_epochs=12,
      weight_decay=0.01,
      eval_strategy="epoch",
      save_strategy="epoch",
  )

  trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_dataset,
      eval_dataset=test_dataset,
      tokenizer=tokenizer,
      data_collator=data_collator,
      compute_metrics=compute_metrics,
  )

  trainer.train()


  eval = trainer.evaluate()

  return model, eval

In [ ]:
aux_df = df.copy()
aux_df.reset_index(drop=True, inplace=True)

aux_df = label_to_int(aux_df, 'label', step1_labels)      # Convert Step 1 Labels
aux_df = label_to_int(aux_df, 'validity', step2_labels) # Convert Step 2 Labels
aux_df = label_to_int(aux_df, 'faults', step3_labels)      # Convert Step 3 Labels

In [ ]:
# Pipeline fine-tuning and evaluation

# Create lists to save models and evaluation results obtained in each fold
model_list_step1 = []
model_list_step2_loss = []
model_list_step2_hazard = []
model_list_step2_constraint = []
model_list_step3_loss = []
model_list_step3_hazard = []
model_list_step3_constraint = []

eval_list_step1 = []
eval_list_step2_loss = []
eval_list_step2_hazard = []
eval_list_step2_constraint = []
eval_list_step3_loss = []
eval_list_step3_hazard = []
eval_list_step3_constraint = []

time_list_step1 = []
time_list_step2_loss = []
time_list_step2_hazard = []
time_list_step2_constraint = []
time_list_step3_loss = []
time_list_step3_hazard = []
time_list_step3_constraint = []

sentence_count_list_step1 = []
sentence_count_list_step2_loss = []
sentence_count_list_step2_hazard = []
sentence_count_list_step2_constraint = []
sentence_count_list_step3_loss = []
sentence_count_list_step3_hazard = []
sentence_count_list_step3_constraint = []


skf = StratifiedKFold(n_splits=5, random_state=random_state, shuffle=True)

for i, (train_index, val_index) in enumerate(skf.split(aux_df['sentence'].to_list(), aux_df['label'].to_list())):
    train_df = aux_df.iloc[train_index]
    val_df = aux_df.iloc[val_index]



    # Step 1
    print('# Fold: ', i+1)
    print('# Step 1')
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df[['sentence','label']], val_df[['sentence','label']], 3)
    end = time.perf_counter()
    time_list_step1.append(end-start)
    model_list_step1.append(model_step)
    eval_list_step1.append(eval_step)
    sentence_count_list_step1.append(len(train_df))


    # Step 2 - Loss
    print('# Fold: ', i+1)
    print('# Step 2 - Loss')
    train_df_loss = train_df[train_df.label.isin([0])] # 'loss' == 0
    val_df_loss = val_df[val_df.label.isin([0])] # 'loss' == 0
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_loss[['sentence','validity']], val_df_loss[['sentence','validity']], 2)
    end = time.perf_counter()
    time_list_step2_loss.append(end-start)
    model_list_step2_loss.append(model_step)
    eval_list_step2_loss.append(eval_step)
    sentence_count_list_step2_loss.append(len(train_df_loss))

    # Step 2 - Hazard
    print('# Fold: ', i+1)
    print('# Step 2 - Hazard')
    train_df_hazard = train_df[train_df.label.isin([1])] # 'hazard' == 1
    val_df_hazard = val_df[val_df.label.isin([1])] # 'hazard' == 1
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_hazard[['sentence','validity']], val_df_hazard[['sentence','validity']], 2)
    end = time.perf_counter()
    time_list_step2_hazard.append(end-start)
    model_list_step2_hazard.append(model_step)
    eval_list_step2_hazard.append(eval_step)
    sentence_count_list_step2_hazard.append(len(train_df_hazard))

    # Step 2 - Constraint
    print('# Fold: ', i+1)
    print('# Step 2 - Constraint')
    train_df_constraint = train_df[train_df.label.isin([2])] # 'constraint' == 2
    val_df_constraint = val_df[val_df.label.isin([2])] # 'constraint' == 2
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_constraint[['sentence','validity']], val_df_constraint[['sentence','validity']], 2)
    end = time.perf_counter()
    time_list_step2_constraint.append(end-start)
    model_list_step2_constraint.append(model_step)
    eval_list_step2_constraint.append(eval_step)
    sentence_count_list_step2_constraint.append(len(train_df_constraint))


    # Step 3 - Loss
    print('# Fold: ', i+1)
    print('# Step 3 - Loss')
    train_df_loss = train_df[train_df.label.isin([0]) & train_df.validity.isin([1])] # 'loss' == 0; 'incorrect' == 1
    val_df_loss = val_df[val_df.label.isin([0]) & val_df.validity.isin([1])] # 'loss' == 0; 'incorrect' == 1
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_loss[['sentence','faults']], val_df_loss[['sentence','faults']], 4)
    end = time.perf_counter()
    time_list_step3_loss.append(end-start)
    model_list_step3_loss.append(model_step)
    eval_list_step3_loss.append(eval_step)
    sentence_count_list_step3_loss.append(len(train_df_loss))

    # Step 3 - Hazard
    print('# Fold: ', i+1)
    print('# Step 3 - Hazard')
    train_df_hazard = train_df[train_df.label.isin([1]) & train_df.validity.isin([1])] # 'hazard' == 1; 'incorrect' == 1
    val_df_hazard = val_df[val_df.label.isin([1]) & val_df.validity.isin([1])] # 'hazard' == 1; 'incorrect' == 1
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_hazard[['sentence','faults']], val_df_hazard[['sentence','faults']], 4)
    end = time.perf_counter()
    time_list_step3_hazard.append(end-start)
    model_list_step3_hazard.append(model_step)
    eval_list_step3_hazard.append(eval_step)
    sentence_count_list_step3_hazard.append(len(train_df_hazard))

    # Step 3 - Constraint
    print('# Fold: ', i+1)
    print('# Step3 - Constraint')
    train_df_constraint = train_df[train_df.label.isin([2]) & train_df.validity.isin([1])] # 'constraint' == 2; 'incorrect' == 1
    val_df_constraint = val_df[val_df.label.isin([2]) & val_df.validity.isin([1])] # 'constraint' == 2; 'incorrect' == 1
    start = time.perf_counter()
    model_step, eval_step = train_model(train_df_constraint[['sentence','faults']], val_df_constraint[['sentence','faults']], 2)
    end = time.perf_counter()
    time_list_step3_constraint.append(end-start)
    model_list_step3_constraint.append(model_step)
    eval_list_step3_constraint.append(eval_step)
    sentence_count_list_step3_constraint.append(len(train_df_constraint))

# Fold:  1
# Step 1

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/867 [00:00<?, ? examples/s]

Map:   0%|          | 0/217 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results

wandb: Enter your choice: 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

# Fold:  1
# Step 2 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/233 [00:00<?, ? examples/s]

Map:   0%|          | 0/58 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  1
# Step 2 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/339 [00:00<?, ? examples/s]

Map:   0%|          | 0/85 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  1
# Step 2 - Constraint

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Map:   0%|          | 0/74 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  1
# Step 3 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/76 [00:00<?, ? examples/s]

Map:   0%|          | 0/23 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  1
# Step 3 - Hazard

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/113 [00:00<?, ? examples/s]

Map:   0%|          | 0/24 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  1
# Step3 - Constraint

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/56 [00:00<?, ? examples/s]

Map:   0%|          | 0/12 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  2
# Step 1

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/867 [00:00<?, ? examples/s]

Map:   0%|          | 0/217 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  2
# Step 2 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/233 [00:00<?, ? examples/s]

Map:   0%|          | 0/58 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  2
# Step 2 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/339 [00:00<?, ? examples/s]

Map:   0%|          | 0/85 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  2
# Step 2 - Constraint

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Map:   0%|          | 0/74 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  2
# Step 3 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/82 [00:00<?, ? examples/s]

Map:   0%|          | 0/17 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  2
# Step 3 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/107 [00:00<?, ? examples/s]

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  2
# Step3 - Constraint

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/57 [00:00<?, ? examples/s]

Map:   0%|          | 0/11 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  3
# Step 1

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/867 [00:00<?, ? examples/s]

Map:   0%|          | 0/217 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  3
# Step 2 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/233 [00:00<?, ? examples/s]

Map:   0%|          | 0/58 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  3
# Step 2 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/339 [00:00<?, ? examples/s]

Map:   0%|          | 0/85 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  3
# Step 2 - Constraint

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Map:   0%|          | 0/74 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  3
# Step 3 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/76 [00:00<?, ? examples/s]

Map:   0%|          | 0/23 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  3
# Step 3 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/116 [00:00<?, ? examples/s]

Map:   0%|          | 0/21 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  3
# Step3 - Constraint

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/52 [00:00<?, ? examples/s]

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  4
# Step 1

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/867 [00:00<?, ? examples/s]

Map:   0%|          | 0/217 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  4
# Step 2 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/233 [00:00<?, ? examples/s]

Map:   0%|          | 0/58 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  4
# Step 2 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/339 [00:00<?, ? examples/s]

Map:   0%|          | 0/85 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  4
# Step 2 - Constraint

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Map:   0%|          | 0/74 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  4
# Step 3 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/83 [00:00<?, ? examples/s]

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  4
# Step 3 - Hazard

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/31 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  4
# Step3 - Constraint

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/52 [00:00<?, ? examples/s]

Map:   0%|          | 0/16 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  5
# Step 1

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/868 [00:00<?, ? examples/s]

Map:   0%|          | 0/216 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  5
# Step 2 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/232 [00:00<?, ? examples/s]

Map:   0%|          | 0/59 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

# Fold:  5
# Step 2 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/340 [00:00<?, ? examples/s]

Map:   0%|          | 0/84 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  5
# Step 2 - Constraint

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/296 [00:00<?, ? examples/s]

Map:   0%|          | 0/73 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  5
# Step 3 - Loss

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/79 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  5
# Step 3 - Hazard

/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/31 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Fold:  5
# Step3 - Constraint

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/tmp/ipykernel_1011/3239734264.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]:'sentence', df.columns[1]:'labels'}, inplace=True)

Map:   0%|          | 0/55 [00:00<?, ? examples/s]

Map:   0%|          | 0/13 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
def get_eval_index(eval_list, time_list, sentence_count_list):
  accuracy_list = []
  precision_list = []
  recall_list = []
  f1_list = []
  score_sum = []
  for eval in eval_list:
    print(eval)
    accuracy_list.append(eval['eval_accuracy'])
    precision_list.append(eval['eval_precision'])
    recall_list.append(eval['eval_recall'])
    f1_list.append(eval['eval_f1'])
    score_sum.append(eval['eval_accuracy']+eval['eval_precision']+eval['eval_recall']+eval['eval_f1'])
  print('###### Average: ######')
  print(f'Accuracy(\u03C3):{np.mean(accuracy_list)}({np.std(accuracy_list)})')
  print('Precision:       ', np.mean(precision_list))
  print('Recall:          ', np.mean(recall_list))
  print(f'F1-Score(\u03C3):{np.mean(f1_list)}({np.std(f1_list)})')
  print('Fine-tuning:     ', np.mean(time_list))
  print('Sentence count:  ', np.mean(sentence_count_list))
  print('Time per sentence:', np.mean(time_list)/np.mean(sentence_count_list))

  print('Highest sum of scores index:', score_sum.index(max(score_sum)))
  print('Best model results:', eval_list[score_sum.index(max(score_sum))])
  print('Best model time per sentence:', time_list[score_sum.index(max(score_sum))]/sentence_count_list[score_sum.index(max(score_sum))])
  print('\n')
  return score_sum.index(max(score_sum))

In [ ]:
#Step 4

model_step4 = SentenceTransformer("all-mpnet-base-v2")

sentence_list = df['sentence'].to_list()
labels_list = [0] * len(sentence_list)
df_step4 = Dataset.from_dict({
    "sentence1": sentence_list,
    "sentence2": sentence_list,
    "label": labels_list,
})

loss_step4 = losses.ContrastiveTensionLossInBatchNegatives(model=model_step4)

args_step4 = SentenceTransformerTrainingArguments(
    output_dir="beds-all-mpnet-base-v2",
    num_train_epochs=12,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    save_strategy="epoch",

)

s_trainer = SentenceTransformerTrainer(
    model=model_step4,
    args=args_step4,
    train_dataset=df_step4,
    loss=loss_step4
)
s_trainer.train()

#model_step4.push_to_hub('beds_step4')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

TrainOutput(global_step=816, training_loss=0.009112151230082792, metrics={'train_runtime': 106.1877, 'train_samples_per_second': 122.5, 'train_steps_per_second': 7.685, 'total_flos': 0.0, 'train_loss': 0.009112151230082792, 'epoch': 12.0})

In [ ]:
# from huggingface_hub import notebook_login

# notebook_login()

In [ ]:
# Show training results and save best models

# Step 1

print('# Step 1')
best_index = get_eval_index(eval_list_step1, time_list_step1, sentence_count_list_step1)
save_path_s1 = "beds_step1_"+model_preset
#model_list_step1[best_index].push_to_hub(save_path_s1)

# Step 2

print('# Step 2 - Loss')
best_index = get_eval_index(eval_list_step2_loss, time_list_step2_loss, sentence_count_list_step2_loss)
save_path_s2_loss = "beds_step2_loss_"+model_preset
#model_list_step2_loss[best_index].push_to_hub(save_path_s2_loss)

print('# Step 2 - Hazard')
best_index = get_eval_index(eval_list_step2_hazard, time_list_step2_hazard, sentence_count_list_step2_hazard)
save_path_s2_hazard = "beds_step2_hazard_"+model_preset
#model_list_step2_hazard[best_index].push_to_hub(save_path_s2_hazard)

print('# Step 2 - Constraint')
best_index = get_eval_index(eval_list_step2_constraint, time_list_step2_constraint, sentence_count_list_step2_constraint)
save_path_s2_constraint = "beds_step2_constraint_"+model_preset
#model_list_step2_constraint[best_index].push_to_hub(save_path_s2_constraint)

# Step 3

print('# Step 3 - Loss')
best_index = get_eval_index(eval_list_step3_loss, time_list_step3_loss, sentence_count_list_step3_loss)
save_path_s3_loss = "beds_step3_loss_"+model_preset
#model_list_step3_loss[best_index].push_to_hub(save_path_s3_loss)

print('# Step 3 - Hazard')
best_index = get_eval_index(eval_list_step3_hazard, time_list_step3_hazard, sentence_count_list_step3_hazard)
save_path_s3_hazard = "beds_step3_hazard_"+model_preset
#model_list_step3_hazard[best_index].push_to_hub(save_path_s3_hazard)

print('# Step 3 - Constraint')
best_index = get_eval_index(eval_list_step3_constraint, time_list_step3_constraint, sentence_count_list_step3_constraint)
save_path_s3_constraint = "beds_step3_constraint_"+model_preset
#model_list_step3_constraint[best_index].push_to_hub(save_path_s3_constraint)

# Step 1
{'eval_loss': 0.4009595811367035, 'eval_accuracy': 0.9216589861751152, 'eval_f1': 0.9206840714369878, 'eval_precision': 0.9180161943319837, 'eval_recall': 0.9272737240282879, 'eval_runtime': 1.5362, 'eval_samples_per_second': 141.258, 'eval_steps_per_second': 9.113, 'epoch': 12.0}
{'eval_loss': 0.23007982969284058, 'eval_accuracy': 0.9585253456221198, 'eval_f1': 0.956369183829138, 'eval_precision': 0.9572283421732627, 'eval_recall': 0.9555780933062881, 'eval_runtime': 1.5095, 'eval_samples_per_second': 143.76, 'eval_steps_per_second': 9.275, 'epoch': 12.0}
{'eval_loss': 0.3858468234539032, 'eval_accuracy': 0.9447004608294931, 'eval_f1': 0.9440713607380274, 'eval_precision': 0.9587628865979382, 'eval_recall': 0.936004970487729, 'eval_runtime': 1.5395, 'eval_samples_per_second': 140.957, 'eval_steps_per_second': 9.094, 'epoch': 12.0}
{'eval_loss': 0.28284236788749695, 'eval_accuracy': 0.9400921658986175, 'eval_f1': 0.9388594342860853, 'eval_precision': 0.9452495974235106, 'eval_recall': 0.9344918955466622, 'eval_runtime': 1.5457, 'eval_samples_per_second': 140.393, 'eval_steps_per_second': 9.058, 'epoch': 12.0}
{'eval_loss': 0.15091687440872192, 'eval_accuracy': 0.9722222222222222, 'eval_f1': 0.9711460855528653, 'eval_precision': 0.9711460855528653, 'eval_recall': 0.9711460855528653, 'eval_runtime': 1.5058, 'eval_samples_per_second': 143.448, 'eval_steps_per_second': 9.298, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.9474398361495135(0.017106722891227884)
Precision:        0.9500806212159121
Recall:           0.9448989537843666
F1-Score(σ):0.9462260271686208(0.016942217786552013)
Fine-tuning:      260.5603994002
Sentence count:   867.2
Time per sentence: 0.3004617151755074
Highest sum of scores index: 4
Best model results: {'eval_loss': 0.15091687440872192, 'eval_accuracy': 0.9722222222222222, 'eval_f1': 0.9711460855528653, 'eval_precision': 0.9711460855528653, 'eval_recall': 0.9711460855528653, 'eval_runtime': 1.5058, 'eval_samples_per_second': 143.448, 'eval_steps_per_second': 9.298, 'epoch': 12.0}
Best model time per sentence: 0.30124143843433204


# Step 2 - Loss
{'eval_loss': 0.4665106534957886, 'eval_accuracy': 0.896551724137931, 'eval_f1': 0.8855263157894737, 'eval_precision': 0.9268292682926829, 'eval_recall': 0.8695652173913043, 'eval_runtime': 0.4357, 'eval_samples_per_second': 133.115, 'eval_steps_per_second': 9.18, 'epoch': 12.0}
{'eval_loss': 0.32412073016166687, 'eval_accuracy': 0.9310344827586207, 'eval_f1': 0.9194444444444444, 'eval_precision': 0.9082321187584346, 'eval_recall': 0.9340028694404592, 'eval_runtime': 0.4463, 'eval_samples_per_second': 129.954, 'eval_steps_per_second': 8.962, 'epoch': 12.0}
{'eval_loss': 0.2486061006784439, 'eval_accuracy': 0.9482758620689655, 'eval_f1': 0.9463459759481961, 'eval_precision': 0.9436274509803921, 'eval_recall': 0.9496894409937888, 'eval_runtime': 0.4219, 'eval_samples_per_second': 137.466, 'eval_steps_per_second': 9.48, 'epoch': 12.0}
{'eval_loss': 0.7100337743759155, 'eval_accuracy': 0.8275862068965517, 'eval_f1': 0.8043184885290149, 'eval_precision': 0.7904040404040404, 'eval_recall': 0.8422619047619048, 'eval_runtime': 0.4392, 'eval_samples_per_second': 132.072, 'eval_steps_per_second': 9.108, 'epoch': 12.0}
{'eval_loss': 0.4072672426700592, 'eval_accuracy': 0.9322033898305084, 'eval_f1': 0.9200542005420054, 'eval_precision': 0.9534883720930232, 'eval_recall': 0.9, 'eval_runtime': 0.4342, 'eval_samples_per_second': 135.885, 'eval_steps_per_second': 9.213, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.9071303331385154(0.04320230567895997)
Precision:        0.9045162501057147
Recall:           0.8991038865174914
F1-Score(σ):0.8951378850506269(0.049344594899171146)
Fine-tuning:      95.11978712240008
Sentence count:   232.8
Time per sentence: 0.40859015086941614
Highest sum of scores index: 2
Best model results: {'eval_loss': 0.2486061006784439, 'eval_accuracy': 0.9482758620689655, 'eval_f1': 0.9463459759481961, 'eval_precision': 0.9436274509803921, 'eval_recall': 0.9496894409937888, 'eval_runtime': 0.4219, 'eval_samples_per_second': 137.466, 'eval_steps_per_second': 9.48, 'epoch': 12.0}
Best model time per sentence: 0.40543602793562356


# Step 2 - Hazard
{'eval_loss': 1.1823599338531494, 'eval_accuracy': 0.7294117647058823, 'eval_f1': 0.6847282696339301, 'eval_precision': 0.6782635467980296, 'eval_recall': 0.6977459016393442, 'eval_runtime': 0.6165, 'eval_samples_per_second': 137.874, 'eval_steps_per_second': 9.732, 'epoch': 12.0}
{'eval_loss': 0.7620679140090942, 'eval_accuracy': 0.8352941176470589, 'eval_f1': 0.8168103448275862, 'eval_precision': 0.8226817042606516, 'eval_recall': 0.812121212121212, 'eval_runtime': 0.6076, 'eval_samples_per_second': 139.901, 'eval_steps_per_second': 9.875, 'epoch': 12.0}
{'eval_loss': 1.0564247369766235, 'eval_accuracy': 0.788235294117647, 'eval_f1': 0.724025974025974, 'eval_precision': 0.7180925666199158, 'eval_recall': 0.7313988095238095, 'eval_runtime': 0.6302, 'eval_samples_per_second': 134.868, 'eval_steps_per_second': 9.52, 'epoch': 12.0}
{'eval_loss': 0.7526300549507141, 'eval_accuracy': 0.8117647058823529, 'eval_f1': 0.793939393939394, 'eval_precision': 0.7989532019704433, 'eval_recall': 0.7900238948626046, 'eval_runtime': 0.6112, 'eval_samples_per_second': 139.067, 'eval_steps_per_second': 9.816, 'epoch': 12.0}
{'eval_loss': 1.0807085037231445, 'eval_accuracy': 0.7738095238095238, 'eval_f1': 0.761613144137416, 'eval_precision': 0.7582352941176471, 'eval_recall': 0.7671941570298235, 'eval_runtime': 0.6222, 'eval_samples_per_second': 135.001, 'eval_steps_per_second': 9.643, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.787703081232493(0.03587495030973356)
Precision:        0.7552452627533375
Recall:           0.7596967950353587
F1-Score(σ):0.75622342531286(0.047477471140858374)
Fine-tuning:      122.69996695020002
Sentence count:   339.2
Time per sentence: 0.36173339313148595
Highest sum of scores index: 1
Best model results: {'eval_loss': 0.7620679140090942, 'eval_accuracy': 0.8352941176470589, 'eval_f1': 0.8168103448275862, 'eval_precision': 0.8226817042606516, 'eval_recall': 0.812121212121212, 'eval_runtime': 0.6076, 'eval_samples_per_second': 139.901, 'eval_steps_per_second': 9.875, 'epoch': 12.0}
Best model time per sentence: 0.36976074810324494


# Step 2 - Constraint
{'eval_loss': 0.2677645981311798, 'eval_accuracy': 0.9459459459459459, 'eval_f1': 0.9005376344086022, 'eval_precision': 0.9005376344086022, 'eval_recall': 0.9005376344086022, 'eval_runtime': 0.5412, 'eval_samples_per_second': 136.729, 'eval_steps_per_second': 9.238, 'epoch': 12.0}
{'eval_loss': 0.0007815795252099633, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.5492, 'eval_samples_per_second': 134.745, 'eval_steps_per_second': 9.104, 'epoch': 12.0}
{'eval_loss': 0.26948103308677673, 'eval_accuracy': 0.9594594594594594, 'eval_f1': 0.9356708200521588, 'eval_precision': 0.9754098360655737, 'eval_recall': 0.90625, 'eval_runtime': 0.5505, 'eval_samples_per_second': 134.427, 'eval_steps_per_second': 9.083, 'epoch': 12.0}
{'eval_loss': 0.2600935697555542, 'eval_accuracy': 0.9594594594594594, 'eval_f1': 0.9387923904052936, 'eval_precision': 0.9497175141242937, 'eval_recall': 0.9288793103448276, 'eval_runtime': 0.5348, 'eval_samples_per_second': 138.365, 'eval_steps_per_second': 9.349, 'epoch': 12.0}
{'eval_loss': 0.27893632650375366, 'eval_accuracy': 0.958904109589041, 'eval_f1': 0.9225874867444326, 'eval_precision': 0.9761904761904762, 'eval_recall': 0.8846153846153846, 'eval_runtime': 0.5258, 'eval_samples_per_second': 138.845, 'eval_steps_per_second': 9.51, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.9647537948907813(0.01836468867136579)
Precision:        0.9603710921577893
Recall:           0.9240564658737629
F1-Score(σ):0.9395176663220974(0.03310441302006205)
Fine-tuning:      111.78222652679999
Sentence count:   295.2
Time per sentence: 0.3786660790203252
Highest sum of scores index: 1
Best model results: {'eval_loss': 0.0007815795252099633, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.5492, 'eval_samples_per_second': 134.745, 'eval_steps_per_second': 9.104, 'epoch': 12.0}
Best model time per sentence: 0.3830160914881355


# Step 3 - Loss
{'eval_loss': 0.8988140821456909, 'eval_accuracy': 0.6521739130434783, 'eval_f1': 0.5096073517126148, 'eval_precision': 0.48511904761904767, 'eval_recall': 0.5642857142857143, 'eval_runtime': 0.1966, 'eval_samples_per_second': 116.973, 'eval_steps_per_second': 10.172, 'epoch': 12.0}
{'eval_loss': 0.5187884569168091, 'eval_accuracy': 0.9411764705882353, 'eval_f1': 0.9373219373219372, 'eval_precision': 0.9523809523809524, 'eval_recall': 0.9333333333333332, 'eval_runtime': 0.1483, 'eval_samples_per_second': 114.621, 'eval_steps_per_second': 13.485, 'epoch': 12.0}
{'eval_loss': 0.6100184917449951, 'eval_accuracy': 0.8695652173913043, 'eval_f1': 0.680952380952381, 'eval_precision': 0.6830357142857143, 'eval_recall': 0.6830357142857143, 'eval_runtime': 0.1948, 'eval_samples_per_second': 118.051, 'eval_steps_per_second': 10.265, 'epoch': 12.0}
{'eval_loss': 1.0909903049468994, 'eval_accuracy': 0.5625, 'eval_f1': 0.530952380952381, 'eval_precision': 0.48214285714285715, 'eval_recall': 0.6875, 'eval_runtime': 0.1355, 'eval_samples_per_second': 118.048, 'eval_steps_per_second': 7.378, 'epoch': 12.0}
{'eval_loss': 0.9161155819892883, 'eval_accuracy': 0.7, 'eval_f1': 0.6590909090909091, 'eval_precision': 0.7678571428571429, 'eval_recall': 0.7166666666666667, 'eval_runtime': 0.1711, 'eval_samples_per_second': 116.912, 'eval_steps_per_second': 11.691, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.7450831202046035(0.13996399456361433)
Precision:        0.6741071428571429
Recall:           0.7169642857142857
F1-Score(σ):0.6635849920060446(0.15267891893524968)
Fine-tuning:      66.21097121859994
Sentence count:   79.2
Time per sentence: 0.8359971113459588
Highest sum of scores index: 1
Best model results: {'eval_loss': 0.5187884569168091, 'eval_accuracy': 0.9411764705882353, 'eval_f1': 0.9373219373219372, 'eval_precision': 0.9523809523809524, 'eval_recall': 0.9333333333333332, 'eval_runtime': 0.1483, 'eval_samples_per_second': 114.621, 'eval_steps_per_second': 13.485, 'epoch': 12.0}
Best model time per sentence: 0.8190179562073149


# Step 3 - Hazard
{'eval_loss': 0.9413321614265442, 'eval_accuracy': 0.7083333333333334, 'eval_f1': 0.5900546821599453, 'eval_precision': 0.5653409090909091, 'eval_recall': 0.6354166666666667, 'eval_runtime': 0.1975, 'eval_samples_per_second': 121.497, 'eval_steps_per_second': 10.125, 'epoch': 12.0}
{'eval_loss': 0.6516924500465393, 'eval_accuracy': 0.8, 'eval_f1': 0.5289473684210526, 'eval_precision': 0.5291005291005292, 'eval_recall': 0.531578947368421, 'eval_runtime': 0.246, 'eval_samples_per_second': 121.927, 'eval_steps_per_second': 8.128, 'epoch': 12.0}
{'eval_loss': 0.9096119403839111, 'eval_accuracy': 0.7619047619047619, 'eval_f1': 0.6229249011857707, 'eval_precision': 0.6314102564102564, 'eval_recall': 0.6416666666666666, 'eval_runtime': 0.1799, 'eval_samples_per_second': 116.731, 'eval_steps_per_second': 11.117, 'epoch': 12.0}
{'eval_loss': 0.6386352181434631, 'eval_accuracy': 0.8387096774193549, 'eval_f1': 0.43968023255813954, 'eval_precision': 0.41035353535353536, 'eval_recall': 0.47619047619047616, 'eval_runtime': 0.2312, 'eval_samples_per_second': 134.081, 'eval_steps_per_second': 8.65, 'epoch': 12.0}
{'eval_loss': 0.54686439037323, 'eval_accuracy': 0.8709677419354839, 'eval_f1': 0.684453781512605, 'eval_precision': 0.6602941176470588, 'eval_recall': 0.7222222222222222, 'eval_runtime': 0.2401, 'eval_samples_per_second': 129.102, 'eval_steps_per_second': 8.329, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.7959831029185869(0.0571107820885501)
Precision:        0.5592998695204577
Recall:           0.6014149958228906
F1-Score(σ):0.5732121931675026(0.08357017765390448)
Fine-tuning:      68.75335556939993
Sentence count:   109.6
Time per sentence: 0.6273116384069337
Highest sum of scores index: 4
Best model results: {'eval_loss': 0.54686439037323, 'eval_accuracy': 0.8709677419354839, 'eval_f1': 0.684453781512605, 'eval_precision': 0.6602941176470588, 'eval_recall': 0.7222222222222222, 'eval_runtime': 0.2401, 'eval_samples_per_second': 129.102, 'eval_steps_per_second': 8.329, 'epoch': 12.0}
Best model time per sentence: 0.6894653359622637


# Step 3 - Constraint
{'eval_loss': 0.17060472071170807, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.1014, 'eval_samples_per_second': 118.394, 'eval_steps_per_second': 9.866, 'epoch': 12.0}
{'eval_loss': 0.1053544282913208, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.0942, 'eval_samples_per_second': 116.795, 'eval_steps_per_second': 10.618, 'epoch': 12.0}
{'eval_loss': 0.23562964797019958, 'eval_accuracy': 0.9375, 'eval_f1': 0.9372549019607843, 'eval_precision': 0.9444444444444444, 'eval_recall': 0.9375, 'eval_runtime': 0.133, 'eval_samples_per_second': 120.345, 'eval_steps_per_second': 7.522, 'epoch': 12.0}
{'eval_loss': 0.25741639733314514, 'eval_accuracy': 0.875, 'eval_f1': 0.8545454545454545, 'eval_precision': 0.9166666666666667, 'eval_recall': 0.8333333333333333, 'eval_runtime': 0.1327, 'eval_samples_per_second': 120.559, 'eval_steps_per_second': 7.535, 'epoch': 12.0}
{'eval_loss': 0.10577329248189926, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.1074, 'eval_samples_per_second': 121.044, 'eval_steps_per_second': 9.311, 'epoch': 12.0}
###### Average: ######
Accuracy(σ):0.9625(0.05)
Precision:        0.9722222222222223
Recall:           0.9541666666666666
F1-Score(σ):0.9583600713012478(0.05731414103195368)
Fine-tuning:      60.44492521119999
Sentence count:   54.4
Time per sentence: 1.1111199487352938
Highest sum of scores index: 0
Best model results: {'eval_loss': 0.17060472071170807, 'eval_accuracy': 1.0, 'eval_f1': 1.0, 'eval_precision': 1.0, 'eval_recall': 1.0, 'eval_runtime': 0.1014, 'eval_samples_per_second': 118.394, 'eval_steps_per_second': 9.866, 'epoch': 12.0}
Best model time per sentence: 1.0531667027321439